extern void starttrigger(void);
extern void endtrigger(void);
extern void randdata(unsigned char * pointer);
extern void readdata(unsigned char * pointer);
extern void printhex(unsigned char * pointer);
extern void endprogram(void);
extern void getstart(unsigned int * pointer);
extern void getruncount(unsigned int * pointer);
extern void initialisekeyflow(unsigned char * pointer);
extern void resetkeyflow(void);
extern void setmaskdataflowstart(unsigned int start);
extern void resetdatafile(void);
