extern void starttrigger(void);
extern void endtrigger(void);
extern void randbyte(unsigned char * pointer);
extern void readbyte(unsigned char * pointer);
extern void printbyte(unsigned char * pointer);
extern void endprogram(void);
extern void getstart(unsigned int * pointer);
extern void getruncount(unsigned int * pointer);
extern void initialisemaskflow(unsigned char * pointer);
extern void resetmaskflow(void);
extern void setmaskflowstart(unsigned int start);
extern void resetdatafile(void);
